name: send
on:
  workflow_dispatch:
    inputs:
      topic:
        description: 'موضوع دلخواه (اختیاری)'
        required: false
        type: string
      text:
        description: 'متن/کپشن دلخواه (اختیاری)'
        required: false
        type: string
      img:
        description: 'لینک عکس یا پرامپت تصویر (اختیاری)'
        required: false
        type: string
  repository_dispatch:
    types: [send_pack]
  schedule:
    - cron: '30 7 * * *'
jobs:
  send:
    runs-on: ubuntu-latest
    env:
      TOKEN: "8672154032:AAEUiCewkNX_1113kfKYp8RY_FFEiZl0lLQ"
      GH_PAT: ${{ secrets.GH_PAT }}
      OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
      GROQ_KEY: ${{ secrets.GROQ_KEY }}
      CUSTOM: ${{ toJSON(github.event.inputs) }}
    steps:
      - name: deps
        run: |
          sudo apt-get update -y > /dev/null 2>&1
          sudo apt-get install -y ffmpeg > /dev/null 2>&1
          pip install pillow > /dev/null 2>&1
      - name: run studio
        run: |
          sleep 5
          curl -s "https://mbms-1356.github.io/forexin-site-/studio.py?v=$(date +%s)" -o studio.py
          python3 studio.py
